import { ClerkProvider } from '@clerk/nextjs';
import { Bebas_Neue } from 'next/font/google';

import { ThemeProvider } from '@/components/providers/theme-provider';
import AuthProvider from '@/components/providers/auth-provider';
import './globals.css';

const font = Bebas_Neue({
  subsets: ['latin'],
  weight: '400', // Specify the only available weight
  display: 'swap', // Optional for performance
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>{children}</AuthProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
